name: Maven Package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn spring-boot:build-image --file pom.xml
    
    - name: Docker login
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Docker tag
      run: docker tag headlines:latest {{ secrets.DOCKER_HUB_USERNAME }}/crawler:{{ github.run_number }}
    - name: Docker push
      run: docker push {{ secrets.DOCKER_HUB_USERNAME }}/crawler:{{ github.run_number }}

   


    
